structure(list(url = "https://globalv1.flywire-daf.com/nglstate/123", 
    status_code = 502L, headers = structure(list(server = "nginx/1.15.10", 
        date = "Sun, 19 Jul 2020 20:34:20 GMT", `content-type` = "text/html", 
        `content-length` = "157", connection = "keep-alive", 
        `strict-transport-security` = "max-age=15724800; includeSubDomains"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 502L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.15.10", date = "Sun, 19 Jul 2020 20:34:20 GMT", 
            `content-type` = "text/html", `content-length` = "157", 
            connection = "keep-alive", `strict-transport-security` = "max-age=15724800; includeSubDomains"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.15.8</center>\r\n</body>\r\n</html>\r\n"), 
    date = structure(1595190860, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.2e-05, 
    connect = 3.3e-05, pretransfer = 0.000121, starttransfer = 0.201578, 
    total = 0.201598)), class = "response")
