#' Convert between filenames and neuroglancer ids
#'
#' @description \code{swc2segmentid} converts an swc filename to a segment id
#'
#' @param x Input file or id
#' @param include.fragment Whether to include the sub identifier of the skeleton
#'   fragment (see details).
#' @return for \code{swc2segmentid} a numeric vector or matrix depending on the
#'   value of \code{include.fragment}
#' @export
#' @name fafbseg-ids
#' @importFrom stringr str_match
#' @examples
#' swc2segmentid("10001654273.1.swc")
#' swc2segmentid(sprintf("10001654273.%d.swc", 0:2), include.fragment=TRUE)
swc2segmentid <- function(x, include.fragment=FALSE) {
  res=str_match(basename(x), "^(\\d+)(\\.(\\d+)){0,1}\\.[Ss][Ww][Cc]$")
  if(isTRUE(include.fragment)) {
    res=res[,c(2,4), drop=FALSE]
    colnames(res)=c("segment", "fragment")
    res
  } else {
    res=res[,2]
  }
  mode(res)='numeric'
  res
}

#' @description \code{segmentid2zip} converts a segment id to the zip file that
#'   contains it
#' @export
#' @rdname fafbseg-ids
#' @examples
#' \donttest{
#' # NB the default segmentation for fafbseg (flywire) no longer implies a local
#' # collection of skeletons, wrap calls in with_segmentation
#' with_segmentation("20190805", segmentid2zip(10001654273))
#' with_segmentation("20190805",
#'   segmentid2zip(swc2segmentid("10001654273.1.swc")))
#' }
segmentid2zip <- function(x) {
  divisor <- find_zip_divisor(getOption("fafbseg.skelziproot"))
  sprintf("%d.zip", as.numeric(x) %/% divisor)
}

#' @description \code{zip2segmentstem} converts a zip file to the initial part
#'   of the segment id i.e. the segment stem (see details).
#'
#' @details Segment ids are unique integers. There are about 8E8 in the current
#'   skeletonisation but it seems that the ids can still be > 2^31 (usually
#'   \code{.Machine$integer.max}). Therefore they will be stored in R as numeric
#'   values or the \code{bit64::integer64} values.
#'
#'   Each segmentation has keen skeletonised however this usually results in
#'   multiple skeleton fragments which have been written out as separate SWC
#'   files: \code{"named <segment id>.<fragment>.swc"}
#'
#'   Each segment id is mapped onto a zip file by dividing by a divisor and
#'   discarding the remainder. Peter Li's data release of 2018-10-02 switched
#'   from 1E5 to 1E6.
#' @export
#' @rdname fafbseg-ids
#' @importFrom tools file_path_sans_ext
zip2segmentstem <- function(x) {
  as.integer(file_path_sans_ext(basename(x)))
}


#' Helper function to turn diverse inputs into neuroglancer segment ids
#'
#' @param x A neuroglancer scene specification form either in raw JSON format
#'   (character vector), the path to a file on disk, a neuroglancer scene URL
#'   (which embeds a JSON scene specification in a single URL), or an R list
#'   generated by parsing one of the above.
#' @param as_character Whether to return segments as character rather than
#'   numeric vector (the default is character for safety).
#' @param include_hidden Whether to include \code{hiddenSegments} (typically for
#'   flywire scenes).
#' @param must_work if \code{TRUE}, the default, then an error will be generated
#'   if the scene has no segments.
#' @param ... Additional arguments passed to \code{\link{ngl_decode_scene}}
#'
#' @return Numeric (or character) vector of segment ids, taken from the first
#'   segmentation layer (with a warning) if the scene contains more than one.
#' @export
#' @family neuroglancer-urls
#' @examples
#' # -> character
#' ngl_segments(c(10950626347, 10952282491, 13307888342))
#' # turns these into numeric
#' ngl_segments(c("10950626347", "10952282491", "13307888342"), as_character=FALSE)
#'
#' \donttest{
#' u="https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/5409525645443072"
#' ngl_segments(u, as_character = TRUE)
#' sc=ngl_decode_scene(u)
#' sc=sc+c("720575940621039145", "720575940626877799")
#' sc
#' }
#'
#' \dontrun{
#' # from clipboard
#' ngl_segments(clipr::read_clip())
#'
#' # URL
#' ngl_segments("<ngl-scene-url>")
#' # path to file on disk
#' ngl_segments("/path/to/scene.json")
#' # R list
#' ngl_segments(scenelist)
#' }
ngl_segments <- function(x, as_character=TRUE, include_hidden=FALSE, must_work=TRUE,  ...) {
  if(is.numeric(x)) {
    if(must_work && (length(x)==0 || !all(valid_id(x))) )
      stop("Sorry. There are invalid segments in ", deparse(substitute(x)))
    return(if(as_character) as.character(x) else as.numeric(x))
  }

  if(is.character(x)) {
    # character vector of segment ids
    if(all(valid_id(x)) || length(x)==0) {
      if(must_work && (length(x)==0))
        stop("Sorry. There are no valid segments in ", deparse(substitute(x)))
      return(if(as_character) as.character(x) else as.numeric(x))
    } else {
      x=ngl_decode_scene(x, ...)
    }
  }

  layers <- ngl_layers(x)
  nls <- ngl_layer_summary(layers)

  nallsegs=if(include_hidden) nls$nsegs+nls$nhidden else nls$nsegs

  if(sum(nallsegs)==0) {
    if(must_work) stop("Sorry. No segments entry in this list!")
    # make an empty list
    segments=numeric()
  } else {
    # extract the chosen layer
    sl <- layers[[min(which(nallsegs>0))]]

    if(sum(nls$nsegs>0) > 1)
      warning("Sorry. More than one segments entry in this list:\n",
        paste(nls$name[nallsegs>0], collapse = '\n'))

    segments=unlist(sl[['segments']])
    if(include_hidden)
      segments <- union(segments, unlist(sl[['hiddenSegments']]))
  }
  if(as_character) as.character(segments) else as.numeric(segments)
}

#' @export
#' @rdname ngl_segments
#' @param value Segment ids in any form understandable by \code{ngl_segments}.
#'   This can include character/numeric/int64 ids, a URL, parsed neuroglancer
#'   scene etc.
#' @description \code{ngl_segments<-} replaces neuroglancer segments in a
#'   neuroglancer scene parsed by \code{\link{ngl_decode_scene}}.
#' @details \code{ngl_segments<-} chooses the FlyWire style
#'   \code{segmentation_with_graph} layer if it exists otherwise the first
#'   visible segmentation layer. Note that \code{hiddenSegment will be removed
#'   in this process}.
#' @examples
#' \donttest{
#' sc <- ngl_decode_scene(u)
#' ngl_segments(sc) <- c("720575940621039145")
#' \dontrun{
#' # make URL and open modified scene in browser
#' browseURL(as.character(sc))
#' }
#' }
`ngl_segments<-` <- function(x, value) {
  # choose first non hidden layer to add segments
  x=ngl_decode_scene(x)
  layers=ngl_layers(x)
  nls=ngl_layer_summary(layers)
  # this is flywire specific, but always what you want
  sel=which(nls$type=="segmentation_with_graph")
  # if we can't find that, then go with standard approach
  if(length(sel)==0)
    sel=which(nls$visible & grepl("^segmentation", nls$type))
  if(length(sel)==0)
    stop("Could not find a visible segmentation layer!")
  if(length(sel)>1) {
    warning('Multiple segmentation layers. Choosing first!')
    sel=sel[1]
  }
  newsegs=ngl_segments(value, as_character = TRUE)
  x[['layers']][[sel]][['segments']]=newsegs
  if(nls$nhidden[sel]>0)
    x[['layers']][[sel]][['hiddenSegments']]=NULL
  x
}

#' @export
#' @description \code{+.ngscene} adds segments to a neuroglancer scene
#' @rdname ngl_decode_scene
#' @param y Segments to add or remove from a neuroglancer scene. Typically as
#'   character vectors or by applying \code{\link{ngl_segments}} to a more
#'   complex object. See examples.
`+.ngscene` <- function(x, y) {
  if(is.list(y))
    stop("I do not yet handle complex input")
  else {
    if(!all(valid_id(y)))
      stop("Please supply valid 64 bit ids!")
    y=ngl_segments(y, as_character = TRUE)
  }

  ngl_segments(x) <- union(ngl_segments(x), y)
  x
}

#' @export
#' @description \code{-.ngscene} removes segments from a neuroglancer scene. It does not complain if the segment is not present.
#' @rdname ngl_decode_scene
`-.ngscene` <- function(x, y) {
  if(is.list(y))
    stop("I do not yet handle complex input")
  else {
    if(!all(valid_id(y)))
      stop("Please supply valid 64 bit ids!")
    y=ngl_segments(y, as_character = TRUE)
  }
  ngl_segments(x) <- setdiff(ngl_segments(x), y)
  x
}

#' Extract and manipulate layers in a neuroglancer scene
#'
#' @param x a neuroglancer scene object (see \code{\link{ngscene}})
#' @param subset an expression (evaluated in the style of subset.dataframe) which defined
#'
#' @export
#' @examples
#' \donttest{
#' u="https://ngl.flywire.ai/?json_url=https://globalv1.flywire-daf.com/nglstate/5409525645443072"
#' sc=ngl_decode_scene(u)
#' sc
#' names(ngl_layers(sc))
#' str(ngl_layers(sc))
#' }
ngl_layers <- function(x, subset=NULL) {
  if(!is.ngscene(x))
    stop("Unable to extract layer information from ", deparse(substitute(x)),
         " as it is not an ngscene object!")

  layers=x[['layers']]
  class(layers)=c("nglayers", "list")
  # record the layers as names for ease of manipulation in R
  # these attributes should be stripped off by ngl_encode_url
  df <- ngl_layer_summary(layers)
  names(layers) <-  if(any(is.na(df$name))) seq_along(layers) else df$name

  e <- substitute(subset)
  if(!is.null(e)) {
    r <- eval(e, df, parent.frame())
    if(is.character(r)) r=match(r, df$name)
    layers=layers[r]
    class(layers)=c("nglayers", "list")
  }

  layers
}

null2na <- function(x) sapply(x, function(y) if(is.null(y)) NA else y,USE.NAMES = F)

ngl_layer_summary <- function(layers) {
  if(is.ngscene(layers))
    layers=layers[['layers']]

  sources=sapply(layers, function(x) unlist(x[['source']],use.names = F)[1])
  types=sapply(layers, "[[", "type")
  # nb layers are visible by default
  visible=sapply(layers, function(y) {vis=y$visible;if(is.null(vis)) TRUE else vis})
  nsegs=sapply(layers, function (y) length(y[['segments']]))
  nhidden=sapply(layers, function (y) length(y[['hiddenSegments']]))
  names=sapply(layers, "[[", "name")
  if(length(names)!=length(layers)) names <- as.character(seq_along(layers))

  st = data.frame(
    name = null2na(names),
    type = null2na(types),
    visible = visible,
    nsegs = null2na(nsegs),
    nhidden = null2na(nhidden),
    source = null2na(sources),
    row.names = NULL,
    stringsAsFactors = F
  )
  st
}

ngl_segmentation <- function(x=getOption('fafbseg.sampleurl'), rval=c('url', 'full'), ...) {
  rval=match.arg(rval)
  layers <- ngl_layers(ngl_decode_scene(x), ...)
  st <- ngl_layer_summary(layers)
  # remove any layers without defined sources
  st=st[!is.na(st$source),,drop=FALSE]
  seglayer=grep('seg', st$type)
  if(length(seglayer)==0) {
    NULL
  } else if(rval=='url') {
    st$source[[seglayer[1]]]
  } else {
    layers[[seglayer[1]]]
  }
}

#' @export
print.ngscene <- function(x, ...) {
  layerdf=ngl_layer_summary(x)
  segs=suppressWarnings(ngl_segments(x, must_work = FALSE))
  segs.all=suppressWarnings(ngl_segments(x, include_hidden = T, must_work = FALSE))

  cat(
    "neuroglancer scene with ",
    nrow(layerdf),
    " layers and ",
    length(segs.all),
    " segments (of which ",
    length(segs),
    " shown)\n",
    sep=""
  )
  print(layerdf)
  invisible(x)
}
